// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebPortal.DbStuff;

#nullable disable

namespace WebPortal.Migrations
{
    [DbContext(typeof(WebPortalContext))]
    [Migration("20250819213353_AddRelationShipMarketplace")]
    partial class AddRelationShipMarketplace
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
