// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebPortal.DbStuff;

#nullable disable

namespace WebPortal.Migrations
{
    [DbContext(typeof(WebPortalContext))]
    [Migration("20250812072105_AddGuitarBaseValues")]
    partial class AddGuitarBaseValues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebPortal.DbStuff.Models.Anime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReleasDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Animes");
                });

            modelBuilder.Entity("WebPortal.DbStuff.Models.Girl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Size")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Girls");
                });

            modelBuilder.Entity("WebPortal.DbStuff.Models.GuitarEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Mark")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ReviewAmount")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Guitars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "ibanez-grg121-card.webp",
                            Mark = 4m,
                            Name = "Ibanez GRG121",
                            Price = 400m,
                            ReviewAmount = 101,
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "les-paul.webp",
                            Mark = 5m,
                            Name = "Gibson",
                            Price = 10000m,
                            ReviewAmount = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "cort-x100-opbk-card.webp",
                            Mark = 2m,
                            Name = "Cort X100 OBPK",
                            Price = 200m,
                            ReviewAmount = 22,
                            Status = 2
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "ibanez-grg121-card.webp",
                            Mark = 4m,
                            Name = "Ibanez GRG121",
                            Price = 400m,
                            ReviewAmount = 101,
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "les-paul.webp",
                            Mark = 5m,
                            Name = "Gibson",
                            Price = 10000m,
                            ReviewAmount = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "cort-x100-opbk-card.webp",
                            Mark = 2m,
                            Name = "Cort X100 OBPK",
                            Price = 200m,
                            ReviewAmount = 22,
                            Status = 2
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "ibanez-grg121-card.webp",
                            Mark = 4m,
                            Name = "Ibanez GRG121",
                            Price = 400m,
                            ReviewAmount = 101,
                            Status = 0
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "les-paul.webp",
                            Mark = 5m,
                            Name = "Gibson",
                            Price = 10000m,
                            ReviewAmount = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "cort-x100-opbk-card.webp",
                            Mark = 2m,
                            Name = "Cort X100 OBPK",
                            Price = 200m,
                            ReviewAmount = 22,
                            Status = 2
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "ibanez-grg121-card.webp",
                            Mark = 4m,
                            Name = "Ibanez GRG121",
                            Price = 400m,
                            ReviewAmount = 101,
                            Status = 0
                        },
                        new
                        {
                            Id = 11,
                            ImageUrl = "les-paul.webp",
                            Mark = 5m,
                            Name = "Gibson",
                            Price = 10000m,
                            ReviewAmount = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 12,
                            ImageUrl = "cort-x100-opbk-card.webp",
                            Mark = 2m,
                            Name = "Cort X100 OBPK",
                            Price = 200m,
                            ReviewAmount = 22,
                            Status = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
