//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CoffeShop {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoffeShop() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebPortal.Localizations.CoffeShop", typeof(CoffeShop).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Coffe.
        /// </summary>
        public static string Index_Add_New_Coffe {
            get {
                return ResourceManager.GetString("Index_Add_New_Coffe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Comments.
        /// </summary>
        public static string Index_Add_New_Comments {
            get {
                return ResourceManager.GetString("Index_Add_New_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Users.
        /// </summary>
        public static string Index_Create_Users {
            get {
                return ResourceManager.GetString("Index_Create_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get back.
        /// </summary>
        public static string Index_Get_Back {
            get {
                return ResourceManager.GetString("Index_Get_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Index_Users {
            get {
                return ResourceManager.GetString("Index_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Coffee.
        /// </summary>
        public static string Index_Your_Coffee {
            get {
                return ResourceManager.GetString("Index_Your_Coffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Comments.
        /// </summary>
        public static string Index_Your_Comments {
            get {
                return ResourceManager.GetString("Index_Your_Comments", resourceCulture);
            }
        }
    }
}
