//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Localizations {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Motorcycles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Motorcycles() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebPortal.Localizations.Motorcycles", typeof(Motorcycles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Brand.
        /// </summary>
        public static string Add_Bike_Brand_Input_Lable {
            get {
                return ResourceManager.GetString("Add_Bike_Brand_Input_Lable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Bike.
        /// </summary>
        public static string Add_Bike_Button_Add {
            get {
                return ResourceManager.GetString("Add_Bike_Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        public static string Add_Bike_Description_Input_Lable {
            get {
                return ResourceManager.GetString("Add_Bike_Description_Input_Lable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Bike.
        /// </summary>
        public static string Add_Bike_Form_Title {
            get {
                return ResourceManager.GetString("Add_Bike_Form_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на URL image bike.
        /// </summary>
        public static string Add_Bike_Image_Link_Input_Lable {
            get {
                return ResourceManager.GetString("Add_Bike_Image_Link_Input_Lable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ADD BIKE.
        /// </summary>
        public static string Index_Button_AddBike {
            get {
                return ResourceManager.GetString("Index_Button_AddBike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ADD BREND AND TYPE.
        /// </summary>
        public static string Index_Button_AddBrendAndType {
            get {
                return ResourceManager.GetString("Index_Button_AddBrendAndType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BREND AND TYPE.
        /// </summary>
        public static string Index_Button_BrendAndType {
            get {
                return ResourceManager.GetString("Index_Button_BrendAndType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Main Motorcycles.
        /// </summary>
        public static string Index_Button_MainMotorcycles {
            get {
                return ResourceManager.GetString("Index_Button_MainMotorcycles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Main WebPortal.
        /// </summary>
        public static string Index_Button_WebPortal {
            get {
                return ResourceManager.GetString("Index_Button_WebPortal", resourceCulture);
            }
        }
    }
}
