//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UnderTheBridge {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UnderTheBridge() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebPortal.Localizations.UnderTheBridge", typeof(UnderTheBridge).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Layout_About_button {
            get {
                return ResourceManager.GetString("Layout_About_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog.
        /// </summary>
        public static string Layout_Catalog_button {
            get {
                return ResourceManager.GetString("Layout_Catalog_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Layout_Contacts_button {
            get {
                return ResourceManager.GetString("Layout_Contacts_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery.
        /// </summary>
        public static string Layout_Delivery_button {
            get {
                return ResourceManager.GetString("Layout_Delivery_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guitar workshops.
        /// </summary>
        public static string Layout_GuitarWorkshops_button {
            get {
                return ResourceManager.GetString("Layout_GuitarWorkshops_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Layout_Language_button {
            get {
                return ResourceManager.GetString("Layout_Language_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string Layout_Payment_button {
            get {
                return ResourceManager.GetString("Layout_Payment_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pickup.
        /// </summary>
        public static string Layout_Pickup_button {
            get {
                return ResourceManager.GetString("Layout_Pickup_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy.
        /// </summary>
        public static string Layout_Policy_button {
            get {
                return ResourceManager.GetString("Layout_Policy_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        public static string Layout_Reviews_button {
            get {
                return ResourceManager.GetString("Layout_Reviews_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serch.
        /// </summary>
        public static string Layout_Serch_Placeholder {
            get {
                return ResourceManager.GetString("Layout_Serch_Placeholder", resourceCulture);
            }
        }
    }
}
