//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Localizations.CompShop {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CompShop {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CompShop() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebPortal.Localizations.CompShop.CompShop", typeof(CompShop).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доставка компьютеров.
        /// </summary>
        public static string Index_Ad_Delivery {
            get {
                return ResourceManager.GetString("Index_Ad_Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на бесплатно от 4.000 Byn.
        /// </summary>
        public static string Index_Ad_Delivery_green {
            get {
                return ResourceManager.GetString("Index_Ad_Delivery_green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Индивидуальная конфигурация.
        /// </summary>
        public static string Index_Advantages_Config {
            get {
                return ResourceManager.GetString("Index_Advantages_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оперативная доставка.
        /// </summary>
        public static string Index_Advantages_Delivery {
            get {
                return ResourceManager.GetString("Index_Advantages_Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Демократичные цены.
        /// </summary>
        public static string Index_Advantages_Price {
            get {
                return ResourceManager.GetString("Index_Advantages_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Быстрая.
        /// </summary>
        public static string Index_Advantages_Speed_1 {
            get {
                return ResourceManager.GetString("Index_Advantages_Speed_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на cборка.
        /// </summary>
        public static string Index_Advantages_Speed_2 {
            get {
                return ResourceManager.GetString("Index_Advantages_Speed_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все устройства.
        /// </summary>
        public static string Index_All_Model {
            get {
                return ResourceManager.GetString("Index_All_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все статьи.
        /// </summary>
        public static string Index_All_News {
            get {
                return ResourceManager.GetString("Index_All_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить.
        /// </summary>
        public static string Index_Button_Add {
            get {
                return ResourceManager.GetString("Index_Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вход.
        /// </summary>
        public static string Index_Entrance {
            get {
                return ResourceManager.GetString("Index_Entrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Главная.
        /// </summary>
        public static string Index_IndexPage {
            get {
                return ResourceManager.GetString("Index_IndexPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наш магазин.
        /// </summary>
        public static string Index_My_Shop {
            get {
                return ResourceManager.GetString("Index_My_Shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статьи.
        /// </summary>
        public static string Index_News {
            get {
                return ResourceManager.GetString("Index_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на О компании.
        /// </summary>
        public static string Index_Page_About {
            get {
                return ResourceManager.GetString("Index_Page_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Каталог.
        /// </summary>
        public static string Index_Page_Catalog {
            get {
                return ResourceManager.GetString("Index_Page_Catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контакты.
        /// </summary>
        public static string Index_Page_Contacts {
            get {
                return ResourceManager.GetString("Index_Page_Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отзывы.
        /// </summary>
        public static string Index_Page_Review {
            get {
                return ResourceManager.GetString("Index_Page_Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Специальные предложения.
        /// </summary>
        public static string Index_Special_Ad {
            get {
                return ResourceManager.GetString("Index_Special_Ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оформите карту «CompShop».
        /// </summary>
        public static string Index_Special_Ad_Basket {
            get {
                return ResourceManager.GetString("Index_Special_Ad_Basket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на И получайте бонусы при покупке в магазинах и на сайте.
        /// </summary>
        public static string Index_Special_Ad_Basket_Desc {
            get {
                return ResourceManager.GetString("Index_Special_Ad_Basket_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Покупайте акционные товары.
        /// </summary>
        public static string Index_Special_Ad_Cart {
            get {
                return ResourceManager.GetString("Index_Special_Ad_Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на И получайте вдвое больше бонусов.
        /// </summary>
        public static string Index_Special_Ad_Cart_Desc {
            get {
                return ResourceManager.GetString("Index_Special_Ad_Cart_Desc", resourceCulture);
            }
        }
    }
}
