//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Localizations.Notes {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Notes {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Notes() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("WebPortal.Localizations.Notes.Notes", typeof(Notes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Index_h2_categories {
            get {
                return ResourceManager.GetString("Index_h2_categories", resourceCulture);
            }
        }
        
        internal static string Index_h2_tags {
            get {
                return ResourceManager.GetString("Index_h2_tags", resourceCulture);
            }
        }
        
        internal static string Index_h2_ads {
            get {
                return ResourceManager.GetString("Index_h2_ads", resourceCulture);
            }
        }
        
        internal static string Edit_button_save {
            get {
                return ResourceManager.GetString("Edit_button_save", resourceCulture);
            }
        }
        
        internal static string Add_button_add {
            get {
                return ResourceManager.GetString("Add_button_add", resourceCulture);
            }
        }
        
        internal static string Add_label_title {
            get {
                return ResourceManager.GetString("Add_label_title", resourceCulture);
            }
        }
        
        internal static string Add_textbox_placeholder_title {
            get {
                return ResourceManager.GetString("Add_textbox_placeholder_title", resourceCulture);
            }
        }
        
        internal static string Add_label_description {
            get {
                return ResourceManager.GetString("Add_label_description", resourceCulture);
            }
        }
        
        internal static string Add_label_imageUrl {
            get {
                return ResourceManager.GetString("Add_label_imageUrl", resourceCulture);
            }
        }
        
        internal static string Add_label_category {
            get {
                return ResourceManager.GetString("Add_label_category", resourceCulture);
            }
        }
        
        internal static string Add_label_tags {
            get {
                return ResourceManager.GetString("Add_label_tags", resourceCulture);
            }
        }
        
        internal static string Add_textbox_placeholder_description {
            get {
                return ResourceManager.GetString("Add_textbox_placeholder_description", resourceCulture);
            }
        }
        
        internal static string Add_textbox_placeholder_imageUrl {
            get {
                return ResourceManager.GetString("Add_textbox_placeholder_imageUrl", resourceCulture);
            }
        }
        
        internal static string Add_dropdawnlist_placeholder_category {
            get {
                return ResourceManager.GetString("Add_dropdawnlist_placeholder_category", resourceCulture);
            }
        }
    }
}
